# Generated by Django 6.0.2 on 2026-09-23 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, upload_to='candidates/'),
        ),
    ]
