# Generated by Django 6.0.2 on 2026-09-24 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0003_cascade_votes_on_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='bio',
            field=models.TextField(blank=True, help_text='Longer profile text. Leave a blank line between paragraphs.', verbose_name='More about'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='summary',
            field=models.TextField(blank=True, help_text='Short introduction shown at the top of the candidate profile.'),
        ),
        migrations.CreateModel(
            name='CandidateGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='candidates/gallery/')),
                ('caption', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='voting.candidate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CandidateLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('facebook', 'Facebook'), ('x', 'X / Twitter'), ('tiktok', 'TikTok'), ('youtube', 'YouTube'), ('linkedin', 'LinkedIn'), ('website', 'Website')], max_length=20)),
                ('url', models.URLField(verbose_name='URL')),
                ('label', models.CharField(blank=True, help_text='Short subtitle, e.g. "Campaign updates".', max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='voting.candidate')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
