import io
import os
from django.conf import settings
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, Image as RLImage
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER

from PIL import Image

from .models import Election, Vote

def get_logo_image():
    base_dir = settings.BASE_DIR
    favicon_path = os.path.join(base_dir.parent, 'frontend', 'public', 'favicon.ico')
    try:
        img = Image.open(favicon_path)
        buf = io.BytesIO()
        img.save(buf, format='PNG')
        buf.seek(0)
        return buf
    except Exception:
        return None

def generate_election_report_pdf(election: Election):
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter, rightMargin=50, leftMargin=50, topMargin=50, bottomMargin=50)

    styles = getSampleStyleSheet()
    
    # Custom Styles
    title_style = ParagraphStyle(
        name='CenterTitle',
        parent=styles['Heading1'],
        alignment=TA_CENTER,
        fontSize=18,
        spaceAfter=12
    )
    subtitle_style = ParagraphStyle(
        name='CenterSubtitle',
        parent=styles['Heading3'],
        alignment=TA_CENTER,
        textColor=colors.dimgrey,
        spaceAfter=6
    )
    footer_style = ParagraphStyle(
        name='CenterFooter',
        parent=styles['Italic'],
        alignment=TA_CENTER,
        textColor=colors.gray,
        fontSize=9
    )
    normal_center = ParagraphStyle(
        name='NormalCenter',
        parent=styles['Normal'],
        alignment=TA_CENTER
    )
    
    elements = []

    # Formal Header
    logo_buf = get_logo_image()
    if logo_buf:
        logo = RLImage(logo_buf, width=0.6*inch, height=0.6*inch)
        logo.hAlign = 'CENTER'
        elements.append(logo)
        elements.append(Spacer(1, 0.1 * inch))

    elements.append(Paragraph("CommonGround Voting Report", subtitle_style))
    elements.append(Paragraph("OFFICIAL ELECTION TALLY", title_style))
    elements.append(Spacer(1, 0.1 * inch))
    
    elements.append(Paragraph(f"<b>Event / Position:</b> {election.title}", normal_center))
    
    start_str = election.starts_at.strftime("%B %d, %Y %I:%M %p")
    end_str = election.ends_at.strftime("%B %d, %Y %I:%M %p")
    
    elements.append(Paragraph(f"<b>Duration:</b> {start_str} to {end_str}", normal_center))
    if election.description:
        elements.append(Spacer(1, 0.05 * inch))
        elements.append(Paragraph(f"<b>Details:</b> {election.description}", normal_center))
    
    elements.append(Spacer(1, 0.4 * inch))

    # Candidates and Votes
    candidates = election.candidates.all()
    for candidate in candidates:
        elements.append(Paragraph(f"Candidate: {candidate.name}", styles['Heading2']))
        elements.append(Spacer(1, 0.1 * inch))

        votes = Vote.objects.filter(election=election, candidate=candidate).select_related('voter').order_by('cast_at')
        
        if votes.exists():
            data = [["Voter Reference #", "Date Submitted"]]
            for vote in votes:
                # Create a formal, functional reference number
                ref_num = f"CG-REF-{election.id:04d}-{vote.id:06d}"
                data.append([ref_num, vote.cast_at.strftime("%B %d, %Y %I:%M %p")])
            
            t = Table(data, colWidths=[3.0 * inch, 3.0 * inch])
            t.setStyle(TableStyle([
                ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#4165de')),
                ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
                ('ALIGN', (0, 0), (-1, -1), 'LEFT'),
                ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                ('BOTTOMPADDING', (0, 0), (-1, 0), 10),
                ('TOPPADDING', (0, 0), (-1, 0), 10),
                ('BACKGROUND', (0, 1), (-1, -1), colors.whitesmoke),
                ('GRID', (0, 0), (-1, -1), 0.5, colors.lightgrey),
                ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.whitesmoke])
            ]))
            elements.append(t)
        else:
            elements.append(Paragraph("No votes cast for this candidate.", styles['Normal']))

        elements.append(Spacer(1, 0.1 * inch))
        elements.append(Paragraph(f"<b>Total votes for {candidate.name}:</b> {votes.count()}", styles['Normal']))
        elements.append(Spacer(1, 0.4 * inch))

    # Footer
    elements.append(Spacer(1, 0.5 * inch))
    event_ref = f"EVT-{election.id:06d}"
    elements.append(Paragraph("--- END OF REPORT ---", normal_center))
    elements.append(Spacer(1, 0.1 * inch))
    footer_text = f"Report generated by CommonGround System<br/>Event Reference #: {event_ref}"
    elements.append(Paragraph(footer_text, footer_style))

    doc.build(elements)
    buffer.seek(0)
    return buffer
